In [1]:
import random
from sklearn.cluster import KMeans
import numpy as np
import PIL
from PIL import Image

img = Image.open('lena.jpg')
img.load()
pixels = np.array(img.getdata(), dtype='int8')

kmeans = KMeans(n_clusters=16, random_state=7).fit(pixels)
centers = kmeans.cluster_centers_
labels = kmeans.labels_
pixels_compressed = pixels
for i in range(len(pixels_compressed)):
    pixels_compressed[i] = centers[labels[i]]
pixels_compressed = pixels_compressed.reshape((1200,1200, 3))
new_img = PIL.Image.fromarray(pixels_compressed, mode='RGB')
new_img.show()


[[ -27 -121  125]
 [ -26 -120  126]
 [ -26 -120  126]
 ...
 [ -86   76   77]
 [ -86   76   77]
 [ -87   75   76]]


KeyboardInterrupt: 

Exception ignored in: 'sklearn.cluster._k_means_fast._relocate_empty_clusters_dense'
Traceback (most recent call last):
  File "<__array_function__ internals>", line 2, in where
KeyboardInterrupt: 
