In [11]:
import PIL
from PIL import Image
import numpy as np
import random

INF = 1e10
img = Image.open('lena.jpg')
img.load()
pixels = np.array(img.getdata())
k = 4
color = [-1]*len(pixels)
centers = []
for i in range(k):
    centers.append([random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)])
# print(centers, '\n')

for i in range(3):
#new clusters
    print('biba')
    nearest = [INF] * len(pixels)
    for l, cent in enumerate(centers):
        dists = (pixels-cent)*(pixels-cent)
    #       print(dists)
        for j in range(len(dists)):
    #         print('snikson deg')
            if np.linalg.norm(dists[j]) < nearest[j]:
                nearest[j] = np.linalg.norm(dists[j])
                color[j] = cent
    # new centers
    print('boba')
    for q, j in enumerate(centers):
        x_sum = 0
        y_sum = 0
        z_sum = 0
        cnt = 0
        for l in range(0, len(pixels)):
            if color[l] == j:
                x_sum += pixels[l][0]
                y_sum += pixels[l][1]
                z_sum += pixels[l][2]
                cnt += 1
        if cnt != 0:
            centers[q] = [int(x_sum/cnt), int(y_sum/cnt), int(z_sum/cnt)]
        else:
            centers[q] = [random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)]
color = np.array(color, dtype='uint8')
color = color.reshape(1200, 1200, 3)
centers = np.array(centers)
print(color)
print(centers, '\n')
print(color.shape)
new_img = PIL.Image.fromarray(color, mode='RGB')
new_img.show()
new_img.save('1color.png')

biba
boba
biba
boba
biba
boba
[[[209 127 120]
  [209 127 120]
  [209 127 120]
  ...
  [209 127 120]
  [209 127 120]
  [209 127 120]]

 [[209 127 120]
  [209 127 120]
  [209 127 120]
  ...
  [209 127 120]
  [209 127 120]
  [209 127 120]]

 [[209 127 120]
  [209 127 120]
  [209 127 120]
  ...
  [209 127 120]
  [209 127 120]
  [209 127 120]]

 ...

 [[ 97  25  63]
  [ 97  25  63]
  [ 97  25  63]
  ...
  [145  60  86]
  [145  60  86]
  [145  60  86]]

 [[ 97  25  63]
  [ 97  25  63]
  [ 97  25  63]
  ...
  [145  60  86]
  [145  60  86]
  [145  60  86]]

 [[ 97  25  63]
  [ 97  25  63]
  [ 97  25  63]
  ...
  [145  60  86]
  [145  60  86]
  [145  60  86]]]
[[213 135 125]
 [ 96  25  64]
 [213  88  94]
 [158  66  85]] 

(1200, 1200, 3)
